project:
  type: book
  output-dir: _book

book:
  title: "How to make your models fast"
  subtitle: "A Systems View of LLM Inference on GPUs"
  author:
    - name: Anshuman Mishra
      url: https://heyyanshuman.com
  date: last-modified
  repo-url: https://github.com/athleticcoder21/inference-book
  repo-actions: [edit, issue]
  search: true
  page-navigation: true
  chapters:
    - index.qmd
    - part: "Kernels"
      chapters:
        - chapters/making-gemv-fast.qmd

format:
  html:
    theme: [cosmo, styles/book.scss]
    toc: true
    toc-depth: 3
    code-copy: true
    code-overflow: wrap
    code-link: true
    anchor-sections: true
    smooth-scroll: true
    number-sections: true
    fig-align: center
    link-external-newwindow: true

execute:
  freeze: auto
